# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_spaceship_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceship',
            name='real_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spaceship',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
