# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine_size', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('production', models.IntegerField()),
                ('mine_size_mod', models.IntegerField()),
                ('level', models.CharField(choices=[('ME', 'Matter Extractor'), ('MD', 'Matter Devourer'), ('MI', 'Matter Inhaler')], default='ME', max_length=50)),
            ],
        ),
    ]
