# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_mine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('production_increase', models.IntegerField()),
                ('random_find_chance', models.IntegerField()),
                ('random_find_increase', models.IntegerField()),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
    ]
