# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0006_auto_20171130_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='prices',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
