# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0007_upgrade_prices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upgrade',
            old_name='prices',
            new_name='price',
        ),
    ]
