# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0008_auto_20171130_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mine',
            name='upgrade',
        ),
    ]
