# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0009_remove_mine_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='real_price',
            field=models.IntegerField(default=0),
        ),
    ]
