# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0004_remove_element_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locationx', models.IntegerField()),
                ('locationy', models.IntegerField()),
                ('locationz', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanetStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Element')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='planet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.PlanetType'),
        ),
    ]
