# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='locationx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='locationy',
            field=models.IntegerField(default=0),
        ),
    ]
