# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20171115_1714'),
        ('companies', '0002_auto_20171115_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_trade', to='companies.Company')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Element')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_trade', to='companies.Company')),
            ],
        ),
    ]
