# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companytrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='money',
            field=models.IntegerField(default=10000),
        ),
    ]
