# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companytrade_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytrade',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
