# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
        ('companies', '0006_auto_20171116_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.Spaceship')),
            ],
        ),
    ]
