# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20171115_1714'),
        ('mining', '0001_initial'),
        ('companies', '0007_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Element')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.Mine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
