# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_mineownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='locationz',
            field=models.IntegerField(default=5000),
        ),
    ]
