# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_mineownership_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineownership',
            name='last_checked',
            field=models.DateTimeField(blank=True),
        ),
    ]
