# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20171122_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_checked',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
