# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_company_last_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineownership',
            name='last_checked',
        ),
        migrations.AddField(
            model_name='mineownership',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
