# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20171122_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
