# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20171122_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytrade',
            name='date_to_finish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companytrade',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
            preserve_default=False,
        ),
    ]
