# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_auto_20171127_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytrade',
            name='ship',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='companies.Ownership'),
            preserve_default=False,
        ),
    ]
