# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_remove_element_state'),
        ('planets', '0002_planet_last_checked'),
        ('companies', '0020_auto_20171127_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_to_finish', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet_buyer_trade', to='planets.Planet')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.Element')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet_seller_trade', to='companies.Company')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Ownership')),
            ],
        ),
    ]
