# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=5)),
                ('weight', models.FloatField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
