# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='rarity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='element',
            name='state',
            field=models.CharField(choices=[('CN', 'Gas'), ('TR', 'Liquid'), ('OC', 'Solid')], default='CN', max_length=3),
        ),
    ]
