# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20171115_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='state',
            field=models.CharField(choices=[('GAS', 'Gas'), ('LIQ', 'Liquid'), ('SOL', 'Solid')], default='GAS', max_length=3),
        ),
    ]
