# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20171115_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='state',
        ),
    ]
